// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Download() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6\"><div class=\"flex flex-col sm:flex-row justify-center items-center gap-4\"><form method=\"post\" class=\"w-full flex flex-col sm:flex-row gap-3 items-center\" hx-post=\"/downloads\" hx-target=\"#download-response\" hx-swap=\"innerHTML\"><label class=\"input input-bordered flex items-center gap-2 w-full sm:w-auto flex-1 min-w-0\"><img src=\"/assets/images/magnet.svg\" class=\"w-5 h-5 sm:w-6 sm:h-6 flex-shrink-0\" alt=\"Magnet icon\"> <input type=\"text\" name=\"magnet-link\" class=\"grow w-full min-w-0\" placeholder=\"Paste magnet link here...\"></label> <label class=\"flex gap-2 label cursor-pointer\"><span class=\"label-text\">zipped?</span> <input type=\"checkbox\" checked=\"checked\" name=\"is-zipped\" class=\"checkbox\"></label> <input type=\"submit\" value=\"Download\" class=\"btn w-full sm:w-auto\"></form></div><div id=\"download-response\" class=\"text-center mt-6 mx-auto max-w-2xl\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
