// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Torrent struct {
	ID        int32
	Name      string
	Hash      int64
	Size      int64
	DateAdded sql.NullTime
}
