// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type File struct {
	ID        string
	Name      string
	FolderID  string
	Size      int64
	Mimetype  string
	Md5       string
	Server    string
	DateAdded sql.NullTime
}

type Folder struct {
	ID             string
	Name           string
	Hash           sql.NullString
	Size           int64
	ParentFolderID sql.NullString
	DateAdded      sql.NullTime
}
