// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type File struct {
	ID        string
	Name      string
	FolderID  string
	Size      int64
	Mimetype  string
	Md5       string
	Server    string
	DateAdded sql.NullTime
	UserID    sql.NullString
}

type Folder struct {
	ID             string
	Name           string
	Hash           sql.NullString
	Size           int64
	ParentFolderID string
	DateAdded      sql.NullTime
	UserID         sql.NullString
}

type User struct {
	ID           string
	PasswordHash string
	CreatedAt    sql.NullTime
	Username     string
}
